# Generated by Django 5.1.5 on 2025-04-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=50)),
                ('Rollno', models.CharField(max_length=50)),
                ('Branch', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Room_Number', models.CharField(max_length=50)),
                ('Phone_Number', models.CharField(max_length=15)),
            ],
        ),
    ]
