# Generated by Django 5.1.5 on 2025-04-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chandana', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Rollno',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Phone_Number',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Room_Number',
            new_name='rollno',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_Name',
            new_name='room_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Year',
            new_name='year',
        ),
    ]
