# Generated by Django 5.1.5 on 2025-04-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandana', '0002_rename_branch_student_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.CharField(max_length=3, unique=True)),
                ('totalbeds', models.IntegerField()),
                ('occupied', models.IntegerField()),
            ],
        ),
    ]
