# Generated by Django 5.1.5 on 2025-04-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandana', '0003_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='roomno',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
