# Generated by Django 5.1.5 on 2025-04-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chandana', '0004_alter_rooms_roomno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room_number',
        ),
    ]
