# Generated by Django 5.1.5 on 2025-04-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandana', '0005_remove_student_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_on', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chandana.rooms')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chandana.student')),
            ],
        ),
    ]
