# Generated by Django 5.1.5 on 2025-04-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chandana', '0006_roomallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='occupied',
        ),
    ]
