# Generated by Django 5.1.5 on 2025-05-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandana', '0007_remove_rooms_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(help_text='Enter Your Email address', max_length=254),
        ),
    ]
