# Generated by Django 5.1.5 on 2025-05-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandana', '0008_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(editable=False, max_length=15),
        ),
    ]
