# Generated by Django 5.1.5 on 2025-05-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandana', '0009_alter_student_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
