# Generated by Django 5.1.5 on 2025-07-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chandana', '0011_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='admission_year',
        ),
    ]
