# Generated by Django 5.1.5 on 2025-07-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chandana', '0012_rename_year_student_admission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(),
        ),
    ]
